services:
  back_end:
    build:
      context: .
      dockerfile: back_End/Dockerfile  # Klasör ismin tam olarak neyse o (Büyük/küçük harf önemli!)
  
  front_end:
    build:
      context: .
      dockerfile: front_End/Dockerfile

  a_i:
    build:
      context: .
      dockerfile: a_i/Dockerfile