services:
  a_i:
    image: ${DOCKER_REGISTRY-}ai
    build:
      context: .
      dockerfile: a_i/Dockerfile

  back_End:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: back_End/Dockerfile

  front_End:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: front_End/Dockerfile